version: "3.8"
services:
  sailingpolar:
    restart: unless-stopped
    build: .
    volumes:
      - ./src:/app
    # ports:
    #   - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
      - TESTENV=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<ghost-faidaipiu>.entrypoints=websecure"
      - "traefik.http.routers.<ghost-faidaipiu>.tls.certResolver=letsencrypt"
      - "traefik.http.routers.<ghost-faidaipiu>.rule=Host(`sailingpolar.lgxerxes.cloud`)"
      - "traefik.http.services.<ghost-faidaipiu>.loadbalancer.server.port=2368"

