[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.fastapi",
    "python311Packages.uvicorn",
    "python311Packages.matplotlib",
    "python311Packages.numpy",
    "python311Packages.pandas",
    "python311Packages.pydantic",
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port 8888"
